### ISSUE TITLE
Action icons clipping through their borders 

### ISSUE THREAD

**Issue by hintxiv** [xivapi/vue-xivtooltips#35]
Hi very cool project!! I'm trying to add tooltips to my site but I'm getting this visual bug:

![image](https://user-images.githubusercontent.com/65056303/102834787-01a1d980-43c3-11eb-89e9-f9067776748f.png)

The html looks something like this: https://gist.github.com/yumiyafangirl/2735d2fa9dd24a275f7b83ed3e1557a0

Any idea what's going wrong here? I think it has something to do with my existing css??

**Comment by SaltedLevity** [comment]
There's an issue with how the caps were implemented with a psuedo element. I've restructured that portion which should hopefully amend the issue, but I need @nonowazu's help with fixing the template/conditional bits in vue. PR is in for him to fix and check! 

In the short term you can just set the caps to not display with the following in your css:
```css
.xivtooltip-inline-image::before {
	display: none !important;
}
.xivtooltip-thumbnail::before {
	display: none !important;
}
```
